name: Run RateBot

on:
  schedule:
    - cron: '0 7 * * *'     # 11:00 Tbilisi time
    - cron: '30 12 * * *'   # 16:30
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r project/requirements.txt

      - name: Run RateBot
        run: python3 project/exchange_rate.py

      - name: Commit updated last_rate.json
        run: |
          git config --global user.name "RateBot"
          git config --global user.email "ratebot@example.com"
          git add project/last_rate.json
          git commit -m "update last rate" || echo "No changes"
          git push

